# 功能开关
switch:
  Debug: off
  # 守护线程 如果启动这个线程会一直保持你的视窗可见
  Guard: off 
# 执行参数
execute:
  # 任务重试时间
  RetryTime: 30
  # 任务循环次数
  TaskLoop: 0
  # 任务失败重试次数
  RetryCount: 10
  # 视频流监控：video 屏幕监控：screen
  Monitor: screen
  


